#!/bin/bash

# chmod +x starter
# chmod +x docker-compose.yml

export HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
docker-compose up -d

if (! lsof -i TCP:3000); then
    npm --prefix kafka-server run start:dev & npm --prefix kafka-client run start:dev
fi